#!/bin/bash
# GitHub Pages und Docker Image Deployment Info

echo "🚀 Zertifikat-Wächter - Deployment Status"
echo "=========================================="
echo ""
echo "✅ GitHub Pages ist konfiguriert!"
echo ""
echo "🌐 Download-Seite:"
echo "   https://techlogia-de.github.io/Zertifikat-Waechter/"
echo ""
echo "🐳 Docker Images werden automatisch gebaut und veröffentlicht:"
echo "   • ghcr.io/techlogia-de/zertifikat-waechter-agent:latest"
echo "   • ghcr.io/techlogia-de/zertifikat-waechter-mcp-server:latest"
echo "   • ghcr.io/techlogia-de/zertifikat-waechter-worker:latest"
echo ""
echo "📦 Workflow:"
echo "   Bei jedem Push zum 'main' Branch werden automatisch:"
echo "   1. Docker Images für alle Services gebaut (AMD64 + ARM64)"
echo "   2. Auf GitHub Container Registry (ghcr.io) veröffentlicht"
echo "   3. GitHub Pages mit der Download-Seite aktualisiert"
echo ""
echo "🔍 Status überprüfen:"
echo "   https://github.com/TechLogia-de/Zertifikat-Waechter/actions"
echo ""
echo "✨ Alles automatisch - keine manuellen Schritte erforderlich!"
echo ""
