#!/bin/bash
# Einfaches Setup für GitHub Pages Deployment

echo "🚀 Zertifikat-Wächter - Agent Downloads bereitstellen"
echo "===================================================="
echo ""
echo "📝 EINFACHE ANLEITUNG:"
echo ""
echo "1️⃣  Gehe zu: https://github.com/DEIN-USERNAME/Zertifikat-Waechter/settings/pages"
echo ""
echo "2️⃣  Bei 'Source' wähle: GitHub Actions"
echo ""
echo "3️⃣  Fertig! Die Seite wird automatisch deployed bei jedem git push"
echo ""
echo "🌐 Deine Download-Seite wird verfügbar sein unter:"
echo "   https://DEIN-USERNAME.github.io/Zertifikat-Waechter/"
echo ""
echo "📦 Oder pushe das Docker Image:"
echo "   ./push-docker-image.sh"
echo ""
echo "✨ Das ist alles - keine Server, kein SSH, komplett kostenlos!"
echo ""
